blank_issues_enabled: false
contact_links:
- name: Questions, feature requests, and more 💬
  url: https://github.com/bytemare/{{.TEMPLATE}}/discussions
  about: Do you need help? Did you make something with {{.TEMPLATE}}? Do you have an idea? Tell us about it!